//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.EastSussexGovUK.TemplateSource.MasterPages.Controls {
    
    
    public partial class ScriptsDesktop {
        
        /// <summary>
        /// publicLibraries control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Escc.ClientDependencyFramework.WebForms.Script publicLibraries;
    }
}
