//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1008.
// 
#pragma warning disable 1591

namespace EsccWebTeam.EastSussexGovUK.GoogleAnalytics {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.eastsussex.gov.uk/Escc.GoogleAnalytics")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GoogleAnalyticsSearchSuggestionsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::EsccWebTeam.EastSussexGovUK.Properties.Settings.Default.EsccWebTeam_EastSussexGovUK_GoogleAnalytics_GoogleAnalytics;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GoogleAnalyticsSearchSuggestionsCompletedEventHandler GoogleAnalyticsSearchSuggestionsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/Escc.GoogleAnalytics/GoogleAnalyticsSearchSuggestion" +
            "s", RequestNamespace="http://www.eastsussex.gov.uk/Escc.GoogleAnalytics", ResponseNamespace="http://www.eastsussex.gov.uk/Escc.GoogleAnalytics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GoogleAnalyticsSearchSuggestions(string searchTerm) {
            object[] results = this.Invoke("GoogleAnalyticsSearchSuggestions", new object[] {
                        searchTerm});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GoogleAnalyticsSearchSuggestionsAsync(string searchTerm) {
            this.GoogleAnalyticsSearchSuggestionsAsync(searchTerm, null);
        }
        
        /// <remarks/>
        public void GoogleAnalyticsSearchSuggestionsAsync(string searchTerm, object userState) {
            if ((this.GoogleAnalyticsSearchSuggestionsOperationCompleted == null)) {
                this.GoogleAnalyticsSearchSuggestionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGoogleAnalyticsSearchSuggestionsOperationCompleted);
            }
            this.InvokeAsync("GoogleAnalyticsSearchSuggestions", new object[] {
                        searchTerm}, this.GoogleAnalyticsSearchSuggestionsOperationCompleted, userState);
        }
        
        private void OnGoogleAnalyticsSearchSuggestionsOperationCompleted(object arg) {
            if ((this.GoogleAnalyticsSearchSuggestionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GoogleAnalyticsSearchSuggestionsCompleted(this, new GoogleAnalyticsSearchSuggestionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GoogleAnalyticsSearchSuggestionsCompletedEventHandler(object sender, GoogleAnalyticsSearchSuggestionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GoogleAnalyticsSearchSuggestionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GoogleAnalyticsSearchSuggestionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591