//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsccWebTeam.EastSussexGovUK.MasterPages.Controls
{


    /// <summary>
    /// Standard metadata to include on the desktop template
    /// </summary>
    public partial class MetadataDesktop
    {
    }
}
