//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1022.
// 
#pragma warning disable 1591

namespace EsccWebTeam.EastSussexGovUK.DeviceDetection {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.eastsussex.gov.uk/EsccWebTeam.DeviceDetection")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IsMobileOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsRobotOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::EsccWebTeam.EastSussexGovUK.Properties.Settings.Default.EsccWebTeam_EastSussexGovUK_DeviceDetection_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IsMobileCompletedEventHandler IsMobileCompleted;
        
        /// <remarks/>
        public event IsRobotCompletedEventHandler IsRobotCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/EsccWebTeam.DeviceDetection/IsMobile", RequestNamespace="http://www.eastsussex.gov.uk/EsccWebTeam.DeviceDetection", ResponseNamespace="http://www.eastsussex.gov.uk/EsccWebTeam.DeviceDetection", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsMobile(string userAgent) {
            object[] results = this.Invoke("IsMobile", new object[] {
                        userAgent});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsMobileAsync(string userAgent) {
            this.IsMobileAsync(userAgent, null);
        }
        
        /// <remarks/>
        public void IsMobileAsync(string userAgent, object userState) {
            if ((this.IsMobileOperationCompleted == null)) {
                this.IsMobileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsMobileOperationCompleted);
            }
            this.InvokeAsync("IsMobile", new object[] {
                        userAgent}, this.IsMobileOperationCompleted, userState);
        }
        
        private void OnIsMobileOperationCompleted(object arg) {
            if ((this.IsMobileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsMobileCompleted(this, new IsMobileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/EsccWebTeam.DeviceDetection/IsRobot", RequestNamespace="http://www.eastsussex.gov.uk/EsccWebTeam.DeviceDetection", ResponseNamespace="http://www.eastsussex.gov.uk/EsccWebTeam.DeviceDetection", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsRobot(string userAgent) {
            object[] results = this.Invoke("IsRobot", new object[] {
                        userAgent});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsRobotAsync(string userAgent) {
            this.IsRobotAsync(userAgent, null);
        }
        
        /// <remarks/>
        public void IsRobotAsync(string userAgent, object userState) {
            if ((this.IsRobotOperationCompleted == null)) {
                this.IsRobotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsRobotOperationCompleted);
            }
            this.InvokeAsync("IsRobot", new object[] {
                        userAgent}, this.IsRobotOperationCompleted, userState);
        }
        
        private void OnIsRobotOperationCompleted(object arg) {
            if ((this.IsRobotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsRobotCompleted(this, new IsRobotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsMobileCompletedEventHandler(object sender, IsMobileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsMobileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsMobileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsRobotCompletedEventHandler(object sender, IsRobotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsRobotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsRobotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591